# kubernetes/helm/transcriber/templates/api.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transcriber-api
  labels:
    app: api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          # Dynamically pulls from your GitHub Container Registry
          image: "{{ .Values.api.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            # Plain-text variables from values.yaml
            - name: POSTGRES_USER
              value: "{{ .Values.database.user }}"
            - name: POSTGRES_DB
              value: "{{ .Values.database.databaseName }}"
            # Secure variable decrypted from Sealed Secrets
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: transcriber-aws-secret
                  key: POSTGRES_PASSWORD
            # Tell the API where to find Redis and the DB inside the cluster
            - name: REDIS_HOST
              value: "transcriber-redis"
            - name: DB_HOST
              value: "transcriber-db-dev.c1we4qs0wcyx.ap-south-1.rds.amazonaws.com"
            # --- NEW HYBRID STORAGE VARS ---
            - name: STORAGE_MODE
              value: "{{ .Values.storage.mode }}"
            - name: S3_VIDEO_BUCKET_NAME
              value: "{{ .Values.storage.bucketName }}"
            - name: AWS_DEFAULT_REGION
              value: "{{ .Values.storage.region }}"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: transcriber-aws-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: transcriber-aws-secret
                  key: AWS_SECRET_ACCESS_KEY
          # Dynamically injects the CPU/Memory limits based on the environment
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          # volumeMounts:
          #   - name: uploads-volume
          #     mountPath: /app/uploads
      # volumes:
      #   - name: uploads-volume
      #     persistentVolumeClaim:
      #       claimName: transcriber-uploads
---
apiVersion: v1
kind: Service
metadata:
  name: transcriber-api
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000