{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: transcriber-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "200m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    # --- The API Gateway Rewrite Trick ---
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: "{{ .Values.ingress.host }}"
      http:
        paths:
          # If URL starts with /api, capture the rest ($2) and strip the /api
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: transcriber-api
                port:
                  number: 80
          # If URL is anything else (frontend), pass it through exactly as is
          - path: /()(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: transcriber-frontend
                port:
                  number: 80
{{- end }}