{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: transcriber-ingress
  annotations:
     {{- toYaml .Values.ingress.annotations | nindent 4 }}  
spec:
  ingressClassName: alb
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: transcriber-api
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: transcriber-frontend
                port:
                  number: 80
{{- end }}