{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: transcriber-ingress
  annotations:
    # Allow uploads up to 200 Megabytes
    nginx.ingress.kubernetes.io/proxy-body-size: "200m"
    # Allow up to 10 minutes for the upload to complete
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
spec:
  ingressClassName: nginx
  rules:
    - host: "{{ .Values.ingress.host }}"
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: transcriber-api
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: transcriber-frontend
                port:
                  number: 80
{{- end }}