---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: transcriber-db-secret
  namespace: transcriber-dev
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCGqfpi5zo6keBdEphGAklxVH6vE2pMnvNyUUJe1Bi/RobDt5KZu+l6xcm/ntTR0747po8L1h2vgYv4hGf6TPyahqrrJZl2jYPhCgh5tQw8ogh5AQO4AghVap7iPPFOsemRXX69RjOEX7xdHHucSnl/YFUFZF6gqYESVFsdsCj9xnVDeQRSy5XQoCFq33UCJQVlc0VLzlkKh47tDTUOf/x6qSLxkYQ32bQrQBeffRBTTaBdlCYzPGDaQf+jGzC9qzRbCW5+4lxGW6k4/6j1O4F3fDdSipcCydjsbCWKyj9KUAZDJpToBQSW4SABofAPv//A4daru3MaARHiOMC1J0ge98tmnLnIDndy6laZoh2Z3DCRF5Tophz1TBS1PxVyBtNXZ/zQmTBIZvWWBaFnnGa23wZeRQv41fIHCwr5l2Wxg+DuCfd6OYitNYdnpQChuR3WFcTmpIoeggsEOUftpT91PBZ6BTJVOpChPtD6mag88hrt1+Bxl4ohw5QYZXybfN8c64d3aRGJhPoz0zSvz7N5aFf9QmGXTkGUIcfz6qVeam5dR6vfAPyUeB2P1oeSXzU5DvFIsOnKpgSyfaLl6MazbTNY/vj2Jb91qfqE4zXHzSVW9N1FFUrpEugfLPB7sdinY8dlZFsUrBhiKcv5uv0Rdvr1Tnec+lXZLJTmJ3VvL0SHw4+ohPNq2k9KC7QnAZvhD5HC/9jqt0uKECA=
  template:
    metadata:
      creationTimestamp: null
      name: transcriber-db-secret
      namespace: transcriber-dev
