---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: transcriber-db-secret
  namespace: transcriber-dev
spec:
  encryptedData:
    DB_PASSWORD: AgAvYzrn77zV0slVnR7AotY6FWa+oVXCjeqchFcyq6yiViSTnkTjQY/AK6TD4A2Fw4Pvr2k7uP2M6177+kTLGYzqEV5l9MZC2VZat3zarKjQnpE3scb49IplVEiMgP27ix8IAmfa7o+0/uVvTawsV6SLTmyX8jzxY7iwoIOImGlXDsm98OazQglOVAxlZmFzwvX5a2/lmDAUCdyhpkPpGOhV7HtgbmU3Bwk4cGh2j51YogRSbaR+kru6rky3OyrqB8Gqh9K0vyZzBOrSyBvxkSqP8aWwa4wR2DVRdmHqaY+u8K7Pu8RFU1JZCkTzDFdyE9KexuOr54MMqZlPeAv2VqjHkDwgnpe/gEHT2e4spfv1b/8rQeu8AR+gIiTnVfhdmAIHBWkArh7RZGJJ1cD8UiJC3LrcX6xYfMkaQ7sIzuC65Gtc2aFxPrN7wW7wesYPGd2rVg90nTr/Rjk1HZmIADze8weRBXtudheTulOW4CT7tsZajuAwpZLFINJ/W86y7xYMKMvKJZ0vldBeH0YD8pfDyRpxA0VR6Ee78hTt5hbdxzKJ6A/fqPPWL7/g7qHE4VxAjWNBkkH3N9hs8tR7VoTDiVjJbg/eauQ0HGzfQet8WjHhgYMwYXCPhoauDazdBsb8JpEQnaMtyPSccZaZo89hoohctrqDN9e63S6FIMm/V9WBP9q6sc8ZkDmk36JRZ+N1j/GR40m70U40QgZf
  template:
    metadata:
      creationTimestamp: null
      name: transcriber-db-secret
      namespace: transcriber-dev
