---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: transcriber-aws-secret
  namespace: transcriber-dev
spec:
  encryptedData:
    HUGGINGFACE_API_KEY: AgB4nDZHjtji1f5OtcLgCo5i0vP1YO7eFWU6mKr+jKxLTn0Itngkh5FFScor8rKx5zo5MhT6vMZUPZ3UluDgWi1Ooytm98PFfPq/gTBNA+x/uXOLZglKP+CEX/YijJwYEk1Yf8PxAQ5sG9SQbz5pIFvGD4kCjqMhh1x1ak9iiwf2jJIXcBymOdKDqyU6Bd5VWaLwLJKQxf42bpFqdEhm/5/FL15pivRXHnoWBr3X1IImLiWGPWDLH2XRKwhMOXSBXpKoo4HjRv3zxFBX7HwDkFXcGK4DeuA8eKJHnK04ABOqS/e3O7PgH579mmGjaAAnwn8UQnX7lM+AtI9rJ4oMDkLz1MB68xivK8fiYdO48CTCaE3R8A3nxAemsCFj2N1kmEgi+yfS1eEetrV0HW8koqBw9Jpm1+iNPKdDgFyltBIlg3OwTg7k2BMoiOwldbXeCMX2vpuJZC0bboTJuxap82oosCEl8h7c6l4dbrKLEIZliXn6PjYZZmUWNeK5YnygLf1mIqswRwmtK18bxt0ddy6+EKgIPntg2lZoIvlH2aCKm0M+OPI6Xde+faii2v1sTyxLbKmGsbI5wDTuCf9//0lb5oH3GU0zP4x/hnhEi/kjFJ7WFp9HEuJWaVRc+V+DLNeawaSvkll1W3qqF3Ene9M7Pdlo5I7VMZJuL/DD0fi21rNosPopD7jZ4+aPOTL2hGhK5FKL9brkuhsov7ldVtnUlN2jetMcIHL003GJWh01bGmRQdHP
  template:
    metadata:
      creationTimestamp: null
      name: transcriber-aws-secret
      namespace: transcriber-dev
