---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: transcriber-db-secret
  namespace: default
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCjL7Nr4fj+4Bfr8iFxK49FYDkoShahnFgf2NPqZs4El/ktEsSrK0VTM9HbMLq1/MwUE5x0F7GCTHxHydWHaIReU4P8rgTnnna6OrIjp2HGy58LQEZjsXsvCTVQ2zndvnGSiFTyAYewJ2DeJkI/IDWjaYGTuWs2VcfBeGLnwEHYzFp9dTdEqdrIA3fGNiGTX/cvVqHju7fqEZCoPnLgj+OhOcMT+Vgr0lkrNkOM20OAjSEEJiJG22U9W2RKQKZVY3cUcjcLbLrDt8f+ZTeSP+grmOrlMV3qpC3jxynl75YANykl2O9HyErP62vV8Gebv7ji0jSzkOXrgaxjxtHKv7T3bTDpdLLH6ZM7cmelVvJ9DpNmXzLOAIdq3pwiJEOMRIstuMCITKAeZGx7Z2zc8BMGscg1ZaMpr5jZw5xmIODyL0BVMXK3CX+IvdoaRZjEsdh+ooiYJ8xEpuHNwrEsgaQ8vRPRFi7W6BWH5ul1+kev/HXsdxeLhFApL48DrN3CyNzHT+rWL7d5RB5fVRDQvth5DbaRcUux01JpLZSs8xRMfrKSLIFFu6pVtUP8wVundxAKu5xjWAneJF9lPghafJEPNEpCAB7jL3EkaQZK3h8PdoTSloOkhYYZ0AXR6fx9lOe4pjqx77sGOOOG/ffbZ8ITfPULIrHFviJS9dRlIGBIyUEkqRhMoYtxgX339OQqgXT3HVEU4/vUJYCTW8U=
  template:
    metadata:
      creationTimestamp: null
      name: transcriber-db-secret
      namespace: default
