environment: "development"
replicaCount: 1

image:
  # This tells Helm to pull the latest code merged into the develop branch
  tag: "1.0.8"

api:
  repository: ghcr.io/kkarka/video-transcriber-api
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "250m"
      memory: "256Mi"

worker:
  repository: ghcr.io/kkarka/video-transcriber-worker

frontend:
  repository: ghcr.io/kkarka/video-transcriber-frontend

ingress:
  enabled: true
  className: "alb" # Change this from nginx to alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
  hosts:
    - host: transcriber.arkadevops.in # Use your subdomain
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: transcriber-frontend
              port:
                number: 80
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: transcriber-api
              port:
                number: 80

# We will encrypt the actual password shortly!
database:
  user: "transcriberadmin"
  databaseName: "transcriberdb?sslmode=require"


storage:
  mode: "s3"
  bucketName: "transcriber-uploads-storage-arka-dev" # Make sure this matches your actual S3 bucket name
  region: "ap-south-1"