apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transcriber-uploads
  labels:
    app: transcriber-uploads
spec:
  accessModes:
    # ReadWriteMany allows multiple pods to read and write at the same time
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi